### ISSUE TITLE
Update to node-fetch 3.0

### ISSUE THREAD

**Issue by solaris007** [greatjapa/node-fetch-retry#10]
Please add support for node-fetch 3.0.0+

https://github.com/node-fetch/node-fetch/blob/main/docs/v3-UPGRADE-GUIDE.md

**Comment by solaris007** [comment]
added PR https://github.com/greatjapa/node-fetch-retry/pull/11

**Comment by greatjapa** [comment]
merged @solaris007. Thanks a lot
